ProjectBlogger/Controllers/BlogController.cs
using System;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectBlogger.Models;
using ProjectBlogger.View_Models;

namespace ProjectBlogger.Controllers
{
        //[Authorize]
        public class BlogController : Controller
        {
            //this gives us access to the data that is in the repositories.  they are fields which don't get initialised 
            //automatically so we need a constructor 
            private readonly IBlogRepository _blogRepository;
            private readonly IUserRepository _userRepository;

            //below is the constructor. pass in the repositories that get injected into the controller as they've been added
            //in the start up configure services.  
            public BlogController(IBlogRepository blogRepository, IUserRepository userRepository)
            {
                //set loocal blog and user repositories to the ones that are going to be injected 
                _blogRepository = blogRepository;
                _userRepository = userRepository;
            }

            //now need an action method to handle the incoming request.  ViewResult shows it's expecting a view to be returned
            //pass the blog repository.AllBlogs so we can see all the blogs when this is called 

            public ViewResult BlogList()
            {
                BlogListViewModel blogListViewModel = new BlogListViewModel();
                blogListViewModel.MyBlogs = _blogRepository.AllBlogs;

                //blogListViewModel.CurrentUser = "Can i get the logged in username to appear here!";
                return View(blogListViewModel);

            }

            //this action is used for when you click on the name of a post it opens up the full details on a new page that you can't 
            //navigate too separately.  
            public IActionResult BlogDetails(int id)
            {
                var blog = _blogRepository.GetBlogById(id);
                if (blog == null)
                    return NotFound();
                return View(blog);
            }

            public IActionResult UserBlogs()
            {
                //want to show signed in user blogs
                //want to show facility to upload / edit blogs 

                return View("Index");
            }
        }
}

ProjectBlogger/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ProjectBlogger.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Contact()
        {
            return View();
        }
    }
}

ProjectBlogger/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project Blogger</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="text-align: center">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area=""  asp-controller="Home" asp-action="Index">Project Blogger</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark"  asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="BlogList">Blog Feed</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/MyBlogs/Index">Your Blogs</a>
                        </li>
                        <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Contact">Contact</a>
                                </li>
                        <partial name="_LoginPartial" />
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2019 - Project Blogger - <a asp-area="" asp-page="/Privacy">Privacy</a>
                </div>
            </footer>

            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>

            @RenderSection("Scripts", required: false)
        </body>
        </html>

    